with-expecter: True
inpackage: false
dir: src/mocks/
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"
all: True
packages:
  sagala-todo/src/delivery/v1http:
    config:
      recursive: True